### ISSUE TITLE
New versions: 1.12.1 / 1.12.2

### ISSUE THREAD

**Issue by JesusMtnez** [dockhippie/minecraft-vanilla#1]
Hello!

I'm looking at your docker images (`minecraft-vanilla` and `minecraft-forge`) and they are spectacular. Thank you! 

I'm trying to use them to setup my own personal servers. Trying to do so, I realized there aren't images for the following minecraft versions:
- `1.12.1`
- `1.12.2`

Are you thinking of making this two versions in the near feature? Maybe I can help you doing it, maybe two pull requests. 

The thing is I don't know exactly which files I have to change to update to a new version update. As far, I have detected:
- `.env` changing `VERSION` parameter
- In `Dockerfile` changing `MINECRAFT_VERSION` environment variable.

If you just one second to help me out, I will be very grateful to you!

**Comment by tboerger** [comment]
Currently all version are separate branches, so hard to do for somebody without write permissions. But thank you for the offer. Let's see if I can publish the new versions on this weekend.

**Comment by tboerger** [comment]
Solved via https://github.com/dockhippie/minecraft-vanilla/commit/edf84a2132f2e7d3935b971fb2ab8fc0016607b7, https://github.com/dockhippie/minecraft-vanilla/tree/1.12.1, https://github.com/dockhippie/minecraft-vanilla/tree/1.12.2

**Comment by tboerger** [comment]
I have also triggered new versions for minecraft-forge:

<img width="820" alt="bildschirmfoto 2018-03-19 um 19 55 29" src="https://user-images.githubusercontent.com/156964/37616335-d8dc1e4e-2baf-11e8-86ef-c60a486117b2.png">

**Comment by JesusMtnez** [comment]
Thank you @tboerger
