### ISSUE TITLE
Enhancement Request: Add mcrcon

### ISSUE THREAD

**Issue by ksmathers** [dockhippie/minecraft-vanilla#5]
This request is to add 'mcrcon' a 12kB tiny little RCON client that can be run from a shell or could be exec'd directly.

https://github.com/Tiiffi/mcrcon

**Comment by tboerger** [comment]
mcrcon is already part of this docker image and it is used at https://github.com/dockhippie/minecraft-vanilla/blob/master/rootfs/usr/libexec/manage-console
